[build]
  command = "npm run build && npm export"
  publish = "out"
  functions = "functions/"
  base = "client"

[[plugins]]
  package = "netlify-plugin-cypress"

[functions]
  node_bundler = "esbuild"